### ISSUE TITLE
[Enhancement]: Add an autoplayer to play all the songs of particular genre

### ISSUE THREAD

**Issue by amelia2802** [amelia2802/Songphile#2]

**Comment by ThienBNguyen** [comment]
Hi can I help?

**Comment by ThienBNguyen** [comment]
as of right now  autoplay on iframe with spotify url is not allow.

**Comment by amelia2802** [comment]
Thank you for letting me know about the current limitation on Spotify URLs. 
Given this restriction, I was wondering if we could explore the possibility of creating an autoplay function that doesn't rely on their inbuilt function. 
Specifically, I was thinking that we could use a custom function to play it when a user interacts with the site. I would love to hear your thoughts on this and whether it would be implementable.
